---
title: "Lecture_10"
author: "Alex Weitzel"
date: "2/6/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#
old code
fna.data <- read.csv("WisconsinCancer.csv")
wisc.df <- data.frame(fna.data) #not necessary i guess
wisc.data <- as.matrix(wisc.df[,3:32])
row.names(wisc.data) <- wisc.df$id

diagnosis <- wisc.df$diagnosis

#

```{r}
wisc.df <- read.csv("WisconsinCancer.csv")
wisc.data <- as.matrix(wisc.df[,3:32])
row.names(wisc.data) <- wisc.df$id
diagnosis <- wisc.df$diagnosis
table(diagnosis) #shows me how many M's and B's

colMeans(wisc.data)
apply(wisc.data,2,sd)

# Perform PCA on wisc.data by completing the following code
#I wanted to scale this because the there is a lot of variance between samples (in that apply function)
wisc.pr <- prcomp(wisc.data, scale. = TRUE)

summary(wisc.pr)
```



plots
```{r}
biplot(wisc.pr)

#PCA 1 vs 2
plot( wisc.pr$x[,"PC1"] , wisc.pr$x[,"PC2"] , col = diagnosis, 
     xlab = "PC1", ylab = "PC2")

#PCA 1 vs 3
plot( wisc.pr$x[,"PC1"] , wisc.pr$x[,"PC3"] , col = diagnosis, 
     xlab = "PC1", ylab = "PC3")

#PCA 1 vs 3
plot( wisc.pr$x[,"PC2"] , wisc.pr$x[,"PC3"] , col = diagnosis, 
     xlab = "PC2", ylab = "PC3")
```

```{r}
pr.var <- (wisc.pr$sdev^2)

head(pr.var)

#proportion of variance
pve <- pr.var / (sum(pr.var))


plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")

barplot(pve, ylab = "Precent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )

## ggplot based graph
library(factoextra)
fviz_eig(wisc.pr, addlabels = TRUE)
```



Dendrogram shiiitttt
```{r}
data.scaled <- scale(wisc.data)

data.dist <- dist(data.scaled)

wisc.hclust <- hclust(d = data.dist)

plot(wisc.hclust)
abline(h = 19, col="red", lty=2)

wisc.pr.hclust <- hclust(dist(wisc.pr$x[,1:3]), method = "ward.D2")

plot(wisc.pr.hclust)

grps <- cutree(wisc.pr.hclust, k = 2)


plot(wisc.pr$x[,1:2], col=grps)
plot(wisc.pr$x[,1:2], col=diagnosis)


```


```{r, include = FALSE}
g <- as.factor(grps)
levels(g)

g <- relevel(g,2)
levels(g)

# Plot using our re-ordered factor 
plot(wisc.pr$x[,1:2], col=g)


library(rgl)
plot3d(wisc.pr$x[,1:3], xlab="PC 1", ylab="PC 2", zlab="PC 3", cex=1.5, size=1, type="s", col=grps)
rglwidget(width = 400, height = 400)

```


```{r, include = FALSE}
wisc.pr.hclust <- hclust(dist(wisc.pr$x[,1:7]), method="ward.D2")
wisc.pr.hclust.clusters <- cutree(wisc.pr.hclust, k=2)


#tables showing the difference of false vs true positives. i think...
table(wisc.pr.hclust.clusters, diagnosis)
table(grps, diagnosis)

```




